### DISCUSSION TITLE
Configuration error

### DISCUSSION THREAD

**Discussion by joselaya** [sebr/bhyve-home-assistant#122] [General]
Hi all, I am new to this device and I am trying to set it up on my HA. 

I have already done the bhyve download (from HACS) but I don't understand what data exactly I need in my Yaml. 

Please any help? Thanks 🙏 

**Describe the new device**
Orbit 21004 B-hyve 

**Logs**
Configuration error

Step 1: Enable debugging.

`configuration.yaml` 

```
bhyve:
  username: email
  password: xxx

sensor:
    - platform: bhyve
    mac: mac divice
    name: myname
    
switch:
  - platform: bhyve
    mac: mac divice
    name: myname
```

**Comment by sebr** [comment]
It should just be:

```yaml
bhyve:
  username: email
  password: xxx

sensor:
  - platform: bhyve
    
switch:
  - platform: bhyve
```
