### DISCUSSION TITLE
How to determine if sprinklers are running - BHyve XR

### DISCUSSION THREAD

**Discussion by whitema** [sebr/bhyve-home-assistant#243] [Q&A]
I'm running three Bhyve XR controllers (total of about 40 circuits), and need to automate a booster pump for all three.   Unfortunately BHyve can't do this natively in softrware and I can't hardwire all three controllers directly to the pump.

I'm employing HA to determine if the sprinklers are running and then tell the switch running the pump to turn on.  Pretty basic stuff.

Is there a generic sensor to indicate that the sprinkler controller has the sprinklers running?   There are sensors for each individual circuit with state, but I'm looking for a simple sensor for the entire controller to make the automation easier than having some massive OR statement with all 40 circuits.  

sensor.<controller>_state provides three states that I've seen so far: auto, manual, off, but not a generic "running" unfortunately.

Anyhow if anyone has any ideas other than my OR statement from hell...

**Comment by sebr** [comment]
This functionality is not provided out of the box with the integration. The `auto`, `manual` and `off` states relate to the configuration of the device to schedule watering (not whether it's actually running).

However, it should be possible to solve your problem with a template `binary_sensor` that is comprised of all the entities which belong to the device(s)... something like this?

```yaml
binary_sensor:
  - platform: template
    sensors:
      any_zone_on:
        friendly_name: "Any Zone On"
        value_template: >
          {% for state in states.switch %}
            {% if state.attributes.device_id == 'abc' and state.state == 'on' %}
              true
            {% endif %}
          {% endfor %}
```
