### DISCUSSION TITLE
Is it Possible to Trigger Manual Watering on Orbit 21004 (Gen1)?

### DISCUSSION THREAD

**Discussion by leefc01** [sebr/bhyve-home-assistant#266] [Q&A] [answered]
Is manual watering exposed  for the Orbit 21004? I noticed that there's `bhyve.start_watering` available for the XD, but not for the 21004.  Apologies if I missed something obvious.

I'm trying to battle squirrels digging up my lawn and wanted to trigger sprinklers based on a motion sensor.  Starting a program doesn't meet my needs as far as I can tell.  The program won't instantly turn on the water as it appears to be tied to specific start times.

**Comment by leefc01** [comment]
I'm going to give this a shot...



```
alias: Backyard - Motion to Water
description: ""
triggers:
  - type: motion
    device_id: [xxxxx]
    entity_id: [xxxxx]
    domain: binary_sensor
    trigger: device
conditions: []
actions:
  - action: bhyve.start_watering
    metadata: {}
    data: {}
    target:
      entity_id: switch.smart_hose_tap_timer_zone
  - delay:
      hours: 0
      minutes: 0
      seconds: 15
      milliseconds: 0
  - action: bhyve.stop_watering
    metadata: {}
    data: {}
    target:
      entity_id: switch.smart_hose_tap_timer_zone
mode: single
```

**Comment by leefc01** [comment, marked as answer]
Got it work.  Took a combination of me re-reading the documentation, searching for examples, and realizing the YAML wasn't the flow of code.  

Leaving the example here for posterity in case it helps anyone looking for examples.

```
alias: Backyard - Motion to Water
description: ""
triggers:
  - type: motion
    device_id: [motion sensor id]
    entity_id: [motion sensor event]
    domain: binary_sensor
    trigger: device
conditions: []
actions:
  - action: bhyve.start_watering
    metadata: {}
    data:
      entity_id: switch.smart_hose_tap_timer_zone
      minutes: 1
mode: single
```
