### DISCUSSION TITLE
Intergration simply not working properly

### DISCUSSION THREAD

**Discussion by ZuluPilgrim** [sebr/bhyve-home-assistant#290] [Q&A]
A while back my integration stopped working properly i.e. the buttons would not update to correct states and battery levels stayed the same. Clicking the button generally turns the tap on (and sometimes off) but the status is not correct. 

Right now my dashboard looks as follows:
![image](https://github.com/user-attachments/assets/4472aac8-cf33-49c8-8087-4906f66bbf77)

But neither tap is on. Also I have but brand new batteries in as they were at 0% but showing the above. If I connect via bluetooth the taps show 100% battery and I can manually start and stop irrigation. 

I can't seem to see any errors in Home Assistant.

When I go into the entities and click the hydranges button, it shows off for a few seconds before changing back to on, even though the valve is off.

My scripts that are run via an automation work just fine.

```
alias: "Irrigation: Water hydrangeas"
description: ""
triggers:
  - trigger: time
    at: "03:00:00"
  - type: turned_off
    device_id: 3559ebed255646457867a91e7a0a85c6
    entity_id: a7a4c3ad999d5be719782aaf0f073faa
    domain: switch
    trigger: device
conditions:
  - condition: and
    conditions:
      - condition: time
        before: "03:20:00"
        weekday:
          - fri
          - sun
          - mon
          - wed
          - tue
          - thu
          - sat
        enabled: true
      - condition: state
        entity_id: input_boolean.irrigation
        state: "on"
actions:
  - action: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.smart_tap_1_zone
mode: single

```
For completeness sake, here is the Hygrandeas button

```
type: horizontal-stack
cards:
  - show_name: true
    show_icon: true
    type: button
    tap_action:
      action: toggle
    entity: input_boolean.irrigation
  - type: vertical-stack
    cards:
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: toggle
        entity: switch.smart_tap_1_zone
        name: "Hydrangeas "
        show_state: false
      - type: gauge
        entity: sensor.smart_tap_1_battery_level
        name: Tap 1 battery level
  - type: vertical-stack
    cards:
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: toggle
        entity: switch.smart_tap_2_zone
        name: Roses
      - type: gauge
        entity: sensor.smart_tap_2_battery_level
        name: Tap 2 battery level
```

Not sure what to try next.
