### DISCUSSION TITLE
Please help! New to home assistant and struggling to get this up and running

### DISCUSSION THREAD

**Discussion by Substarbo** [sebr/bhyve-home-assistant#67] [Q&A]
Please show me where I am going wrong. I have downloaded the integration from HAC's but can not get the configuration to work. I get the error: duplicated mapping key at line 45, column -28:
    sensor:
    ^

bhyve:
  username: !secret bhyve_xxxx@gmail.com 
  password: !secret bhyve_password

sensor:
  - platform: bhyve

switch:
  - platform: bhyve

**Comment by sebr** [comment]
Home assistant uses [YAML syntax](https://www.home-assistant.io/docs/configuration/yaml/). It seems like you've declared `sensor:` twice.

Your config should look like this:

```
bhyve:
    username: !secret bhyve_xxxx@gmail.com
    password: !secret bhyve_password

sensor:
    - platform: bhyve
switch:
    - platform: bhyve
```

If you have other configurations of `sensor` or `switch` then you need to combine them.
