### ISSUE TITLE
Need Setup help Please

### ISSUE THREAD

**Issue by ae8u** [sebr/bhyve-home-assistant#10]
I had this working and then I crashed my system and I am trying to rebuild it. Now for the life of me I cannot figure out how I got it to work the last time. I do not have something set correctly in my yaml files, but not sure what. It is not seeing the B-hyve controller, which has a fixed IP address set by my router. How do I get HA to recognize the controller?

Thanks,
Mike

**Comment by sebr** [comment]
Hi Mike,
The integration polls the b-hyve servers and don't interact directly with your devices. Are you able to see your devices in the app or when visiting https://my.orbitbhyve.com/ ?

If you can't see them here, there are probably other connectivity issues with your network/devices.

If you can, then it's likely a configuration error in HA. You'll probably need all of these:

```
bhyve:
  username: !secret bhyve_username
  password: !secret bhyve_password

switch:
  - platform: bhyve

binary_sensor:
  - platform: bhyve

sensor:
  - platform: bhyve
```

If you don't add the integration platforms then the relevant entities won't be added to HA.
