### ISSUE TITLE
3.0.0 beta should carry over config from `configuration.yaml`

### ISSUE THREAD

**Issue by fireheadman** [sebr/bhyve-home-assistant#134]
redownloaded and selected Beta version (latest).
installed it, then restarted.

everything pertaining to orbit was unavailable.

If there is something I missed, please let me know and will retry

**Comment by sebr** [comment]
Hi @fireheadman - any more details you can provide about what you've looked at would be helpful. For example, in the Integrations & Services settings page is BHyve listed? If not, can you select "+ Add integration" and add a BHyve config? It's possible the config wasn't carried over correctly.

Separately, were there any logs you could provide?

**Comment by fireheadman** [comment]
I did not see it in the integrations page, was expecting to see that.
I will go back through the process once more this evening/tomorrow.

**Comment by disforw** [comment]
I just upgraded to your beta, rebooted and manually added via config flow. You must remove all elements of this integration from the config.yaml file before adding it config flow (the transfer over is broke). I can confirm that this is working perfectly and no errors in the log file!!! Great job! I have a 6 zone controller, a 2 zone XD hose controller, and 5 flood sensors (see attached image). ALL DEVICES and entities are working perfectly!
![542A8BB6-160F-4773-B0C0-905F2898EA55](https://user-images.githubusercontent.com/24241104/170154940-800221b0-b320-469a-9bf3-57e7693e4924.jpeg)

**Comment by AnthonyBe** [comment]
I'm a little confused here.

I was using v2.2.3 of the BHyve integration just fine and then it stopped working entirely when I updated HACS to v1.25.1

I've tried updating the BHyve integration to 3.0.0 beta 1, and removed the manual YAML config from my configuration.yaml, but the integration isn't appearing anywhere for me to add.
I've also tried removing the BHyve repository from HACS, restarting, and re-adding, but there was no change.

I'm not sure what is meant by 'manually added via config flow' in the post above?

**Comment by disforw** [comment]
Sorry, here are the steps I took when upgrading from 2.2.3 to 3.0.0B1.

1. download upgraded code via HACS
2. reboot
3. +Add Integration Orbit BHyve (Settings -> Integrations)
4. Worked, looked good!
5. Rebooted and it broke (errors indicating could not load platform from sensor.yaml...)
6. removed all related code from configuration.yaml including sensor and switch
7. deleted all related unavailable entities (to get a fresh start)
8. rebooted, working great ever since

**Comment by fireheadman** [comment]
I uninstall the manual (non Beta) version from HACs
Renamed all my yaml files to *.DISABLED
rebooted
downloaded the latest Beta version in HACS
rebooted

I can see bhyve in /config/custom_components/bhyve   (even watched it download while doing a tail -f home-assistant.log)
rebooted once more

I do not see the integration in HA... searched for Orbit and Bhyve, even went through the entire list.
How do we get it to pop in there?

**Comment by fireheadman** [comment]
I like it!.... really no change from previous other than having devices and the integration inside HA
Still waiting to bring water online at house, then my graphs will populate
![image](https://user-images.githubusercontent.com/19847195/170349837-f7fe25aa-ecb8-475c-b9f0-f8349602ed31.png)

![image](https://user-images.githubusercontent.com/19847195/170350001-a6e1193f-eadc-433a-bccd-f366dfb66510.png)

![image](https://user-images.githubusercontent.com/19847195/170350033-8c749130-9cf7-4c89-bfed-68463f8bac50.png)

**Comment by fireheadman** [comment]
oh and the sensors I created for the graph are:

```
- sensor:
  - name: "Orbit: Garden Hose Timer (Water Used)"
    unit_of_measurement: "gal"
    state_class: measurement
    icon: mdi:water-pump
    state: "{{ state_attr('sensor.zone_history', 'consumption_gallons') }}"
```
```
- sensor:
  - name: "Orbit: Tiered Garden Drip (Water Used)"
    unit_of_measurement: "gal"
    state_class: measurement
    icon: mdi:water-pump
    state: "{{ state_attr('sensor.drip_zone_history', 'consumption_gallons') }}"
```
```
- sensor:
  - name: "Orbit: Tiered Garden Spray (Water Used)"
    unit_of_measurement: "gal"
    state_class: measurement
    icon: mdi:water-pump
    state: "{{ state_attr('sensor.spray_zone_history', 'consumption_gallons') }}"
```
