### ISSUE TITLE
Set manual preset time

### ISSUE THREAD

**Issue by timknowlden** [sebr/bhyve-home-assistant#147]
**Describe the bug**
Call service to set manual preset time does not change the default time from 300seconds.

**Expected behaviour**
```
service: bhyve.set_manual_preset_runtime
data:
  entity_id: switch.hose_zone
  minutes: 15
```

Results in:

```
device_class: switch
icon: mdi:water-pump
friendly_name: Hose zone
device_name: ****
device_id: ****
zone_name: Hose
smart_watering_enabled: false
manual_preset_runtime: 300
program_e:
  enabled: true
  name: Smart Watering
  is_smart_program: true
```

**BHyve devices**
Bhyve 4 sprinkler station
