### ISSUE TITLE
Sensor Rain delay errors on startup

### ISSUE THREAD

**Issue by TheGardenMonkey** [sebr/bhyve-home-assistant#15]
The following appears in my home-assistant log upon every restart for the `rain_delay_*_remaining` and `rain_delay_*_finishing` for each device:

```
2020-05-25 14:03:44 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.rain_delay_deck_finishing fails
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 470, in async_device_update
    await self.async_update()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/template/sensor.py", line 224, in async_update
    self._state = self._template.async_render()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/template.py", line 228, in async_render
    return compiled.render(kwargs).strip()
  File "/srv/homeassistant/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/srv/homeassistant/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/srv/homeassistant/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
```

**Comment by sebr** [comment]
Those `rain_delay_finishing` and `rain_delay_remaining` sensor examples are a bit... fragile. They were indicative only.

However - I do have a `python_script` which creates and updates sensors to do this which I'll package up into a release. Will need a day or two to publish a beta release.

**Comment by sebr** [comment]
@TheGardenMonkey turns out HACS doesn't support bundling both a custom component and a python script so you'll need to install it manually. Check out the docs here: https://github.com/sebr/bhyve-home-assistant#python-script

NB: You'll need to upgrade to version [0.2.0-alpha.2](https://github.com/sebr/bhyve-home-assistant/releases/tag/0.2.0-alpha.2)

**Comment by TheGardenMonkey** [comment]
I can't figure out how to do the alpha / beta installs in HACS anymore lol. Any advice for how to do the upgrade in HACS or do I have to do it manually? 

...And a huge thank you for this. I was giving up that we would ever get the bhyve ecosystem into HA. I have 3 active timers (i have a boxed one as well) and I would definitely like to help with any beta testing (or coding) you need for enhancements.

**Comment by sebr** [comment]
Go to HACS → Orbit BHyve → Reinstall → Show Beta Versions
<img width="383" alt="Screen Shot 2020-05-27 at 10 57 01 am" src="https://user-images.githubusercontent.com/81972/82964436-cd229680-a008-11ea-9db0-3c64ee179ec3.png">
<img width="789" alt="Screen Shot 2020-05-27 at 10 57 31 am" src="https://user-images.githubusercontent.com/81972/82964464-df9cd000-a008-11ea-8368-513faff43e98.png">

**Comment by sebr** [comment]
Did you manage to test this at all @TheGardenMonkey ? Keen for some feedback before releasing to the wild :)

**Comment by TheGardenMonkey** [comment]
I did but it isn't updating, it is creating the sensors but just getting None for the next watering. I will attempt to debug in the morning.

**Comment by TheGardenMonkey** [comment]
From what I see it is looking for an attribute that isn't on my devices. Line 40:
```python
for timestamp in zone.attributes.get("watering_program", []) or []:
```

...my devices do not have a watering_program attribute as far as I can tell.  Instead there is a "switch.program-name_program" that has a start_times and days attribute that looks like it should be parsed for the correct time.

Are you on discord, maybe I can send you some of the details of what mine look like? I can also give a shot updating it to support mine.

**Comment by sebr** [comment]
Yep i'm in the HA server as `sebr`. Ping me there!

**Comment by AlexVercammen** [comment]
I've installed your HACS last weekend and it was a flawless installation. The only struggle I had was with the sensor templates.
They would only refresh after restarting. So I've created then added the "entity_id: sensor.time" to the templates. Also I change the timestamp to a custom and just get the day of the next watering.
I have NOT updated to your latest version yet! So this could be irrelevant. (Installed: 0.1.13)

```
sensor:
  - platform: time_date
    display_options:
      - time
  - platform: template
    sensors:
      rain_delay_lawn_remaining:
        friendly_name: "Rain Delay Remaining"
        entity_id: sensor.time
        unit_of_measurement: "h"
        availability_template: "{{ states('binary_sensor.rain_delay_b_hyve_timer') != 'unavailable' }}"
        value_template: "{{ ((as_timestamp(state_attr('binary_sensor.rain_delay_b_hyve_timer', 'started_at')) + state_attr('binary_sensor.rain_delay_b_hyve_timer', 'delay') * 3600 - as_timestamp(now())) / 3600) | round(0) }}"

      lawn_next_watering:
        friendly_name: "Next watering"
        entity_id: sensor.time
        availability_template: "{{ states('switch.backyard_zone') != 'unavailable' }}"
        value_template: >-
          {% set program = state_attr('switch.backyard_zone', 'watering_program') -%}
          {% if program and (program | count > 0) %}
            {{ as_timestamp(program[0]) | timestamp_custom('%A',false) }}
          {% else %}
            unknown
          {% endif %}
```
