### ISSUE TITLE
not getting switches

### ISSUE THREAD

**Issue by GHSTUDIO1** [sebr/bhyve-home-assistant#36]
I installed this addon, added the following to my config.yaml

```
bhyve:
  username: me@whatever.com
  password: whocares

switch:
   - platform: bhyve 

sensor:
   - platform: bhyve
```

I see the sensors for my three orbit controllers, but I can't find any switch (or zone) entities.
