### ISSUE TITLE
Feature Request: ability to modify program start times

### ISSUE THREAD

**Issue by foxy82** [sebr/bhyve-home-assistant#38]
One of my main frustrations with the orbit bhyve is that if I want to water at dawn there is no way to do this without manually adjusting the program start time as the dawn time changes over the seasons.

It would be amazing if I could do this using home assistant.

**Comment by sebr** [comment]
@foxy82 have you considered turning off all BHyve programs and using HA to trigger watering? You could do this with a simple automation:

```yaml
automation:
  - alias: Water at dawn
    trigger:
      - platform: sun
        event: sunrise
    action:
      - service: bhyve.start_watering
        data:
          entity_id: switch.lawn_zone
          minutes: 10
```

This would mean you'd lose the "Smart Watering" capabilities which come with the service.
