### ISSUE TITLE
No state data

### ISSUE THREAD

**Issue by brucehvn** [sebr/bhyve-home-assistant#39]
I'm running Hassio 0.114.4.  I've installed your integration via HACS and added the configuration params per the instructions.  After restarting HA, it creates the entity sensors, switches, etc., but the states are all "unavailable".

It seemed to pick up the name of my timer, which is "shed_misting".  I have one zone called "Zone 1".  I see a `switch.zone` entity which I'm guessing is that zone, but it also has the state of "unavailable".  Attempting to turn on that switch via the service call does nothing. I've tried restarting HA a couple times.  There's nothing in the log file related to the bhyve component at all.

This is a brand new bhyve with the wi-fi hub.  It's working from the app.
```
bhyve:
  username: !secret bhyve_username
  password: !secret bhyve_password

switch:
  - platform: bhyve

sensor:
  - platform: bhyve
```
Is there something I'm missing?
Timer firmware version: 41
Hub firmware version: 0030
