### ISSUE TITLE
Feature request: switch to turn individual sensors on/off

### ISSUE THREAD

**Issue by dreedijk** [sebr/bhyve-home-assistant#42]
It would be great if it would be possible to turn individual sensors on and off for a configurable amount of time.
I have 9 BHyve Hose Faucet Timers (sensors) which are all part of the same zone, I have no automated watering program and manually turn the devices on when needed for the set amount of minutes.

**Comment by sebr** [comment]
@dreedijk how does one combine multiple Faucet Timer devices into a single zone?

In my setup, where I have 3 faucet timers, they each have their own zone, and thus their own switch which can be triggered individually.

**Comment by sebr** [comment]
@dreedijk anything further to add to this? I can't proceed without more info 😄

**Comment by dreedijk** [comment]
You are absolutely right :-) I have contacted b-hyve support to explain to me why I cannot create any zones (so I'm stuck with one that contains all devices). I'm still waiting for a reply ...
As for now, as mentioned they are all in 1 zone. I don't use any programs, but turn them on on-demand. In other words, I select a single device, set the timer (total minutes) and turn it on. This would be great to have as a HA button or ...

**Comment by sebr** [comment]
You can do this - you'll just need to call a service, eg:

```
type: button
name: Start watering
show_state: false
tap_action:
  action: call-service
  service: script.bhyve.start_watering
  service_data:
    entity_id: switch.my_zone_switch
    minutes: 5
```
