### ISSUE TITLE
Set minutes service bhyve.start_watering

### ISSUE THREAD

**Issue by Flavio5** [sebr/bhyve-home-assistant#47]
Hi, it is possible to set the minutes of bhyve.start_watering service (for example in an automation) from an input_number?

I want to choose the minutes of manual irrigation from lovelace and so start the irrigation (through a script or an automation).

Thanks

**Comment by sebr** [comment]
Sure... take a look at the documentation for [`input_number`](https://www.home-assistant.io/integrations/input_number#automation-examples).

It might look something like:

```yaml
input_number:
  irrigation_minutes:
    name: Irrigation time
    initial: 10
    min: 1
    max: 60
    step: 1

automation:
  - alias: Run irrigation
    trigger:
      platform: state
      entity_id: input_number.irrigation_minutes
    action:
      - service: bhyve.start_watering
        data:
          entity_id: switch.my_zone
          minutes: "{{ states('input_number.irrigation_minutes') | int }}"
```

But... you probably want this to be a script which you can trigger from a lovelace card. I'll leave that up to you to do in a manner which is relevant to your configuration :)
